### ISSUE TITLE
`ConfigPostProcessor` replaces dependency service and therefore removes factory mapping

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-zendframework-bridge#51]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.1

#### Summary

Hey guys, I am experiencing an issue with mezzio-only projects where the `ConfigPostProcessor` provided from this project replaces keys and values in the project configuration and by doing that, destroying the factory mapping for a zendframework service.

I've tried this with an mvc application but it seems that there are no such config replacements (because I could not reproduce this in there)?

#### Current behavior

The `ConfigPostProcessor` changes the factory mapping for the servicemanager as follows:

RAW configuration:
```php
[
    'factories' => [
        'Zend\Form\Factory' => 'SomeZendFormFactoryFactory',
    ],
]
```

Post processed configuration:
```php
[
    'factories' => [
        'Laminas\Form\Factory' => 'SomeZendFormFactoryFactory',
    ],
]
```

Now, the non-migrated module wants to retrieve the service from the servicemanager.
The servicemanager searches for the factory for `Zend\Form\Factory` as provided, but the post processed configuration does not know the `Zend\Form\Factory` factory anymore.

#### How to reproduce

I've created two repositories to provide an example on how the bug occurs:

Project (would be enough to check this out):
https://github.com/boesing/mezzio-project

Module which is not yet migrated to laminas:
https://github.com/boesing/zend-form-module

Run `composer serve` in the `mezzio-project` project and call `http://localhost:8080`. The error will occur.

#### Expected behavior

The proper laminas service should be instantiated. However, as this is a mapping issue for the service manager, I am not sure if this can be solved that easy. I guess there should be a dedicated replacement for all service- and pluginmanager configurations to solve that issue. Or probably you guys have another idea.

**Comment by weierophinney** [comment]
In your project, is the laminas-dependency-plugin installed?

**Comment by boesing** [comment]
Just to make it more transparent (as we are chatting in slack):
Yes: https://github.com/boesing/mezzio-project/blob/bug/config-post-processor-replaces-service-from-servicemanager/composer.json#L45

**Comment by weierophinney** [comment]
Root cause analysis:

Normally, laminas-zendframework-bridge kicks in in two ways. First, via autoloading, it will see a request for `Zend\Form\Factory`, alias that to `Laminas\Form\Factory`, and carry on. This works fine.

The other part of the work is when requesting a service from the container. That logic works when there _service aliases_ exist, aliasing the legacy service name to the new service name. In this particular scenario, the zend-form library never defined a `Zend\Form\Factory` service for the container, so laminas-form does not contain an alias for it. Due to the configuration rewriting that occurs, since there is no alias present for `Zend\Form\Factory`, the factory map gets rewritten, and now any attempts to retrieve it fail, because the container only knows about `Laminas\Form\Factory`.

It looks like we may need to check to see if an alias exists for a class before attempting to rewrite the mapping during configuration post processing.
