### ISSUE TITLE
Incompatibility with composer 2.2.0RC1

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-zendframework-bridge#89]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.4.0

#### Summary

https://github.com/composer/composer/issues/10349
With composer 2.2.0, the autoloading is already provided for plugins during installation of dependencies.
Due to this fact, `vendor/autoload.php` might be missing and thus, the autoloader will crash.

#### Current behavior

```
Exception trace:
  at /Users/max/git/hardware/core-api/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:75
 Laminas\ZendFrameworkBridge\Autoloader::getClassLoader() at /Users/max/git/hardware/core-api/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:47
 Laminas\ZendFrameworkBridge\Autoloader::load() at /Users/max/git/hardware/core-api/vendor/laminas/laminas-zendframework-bridge/src/autoload.php:3
 require() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Autoload/AutoloadGenerator.php:1422
 Composer\Autoload\composerRequire() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Plugin/PluginManager.php:244
 Composer\Plugin\PluginManager->registerPackage() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Installer/PluginInstaller.php:79
 Composer\Installer\PluginInstaller->Composer\Installer\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/FulfilledPromise.php:28
 React\Promise\FulfilledPromise->then() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:134
 React\Promise\Promise::React\Promise\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/FulfilledPromise.php:42
 React\Promise\FulfilledPromise->done() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:135
 React\Promise\Promise::React\Promise\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/FulfilledPromise.php:42
 React\Promise\FulfilledPromise->done() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:66
 React\Promise\Promise::React\Promise\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/FulfilledPromise.php:42
 React\Promise\FulfilledPromise->done() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:135
 React\Promise\Promise::React\Promise\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/FulfilledPromise.php:42
 React\Promise\FulfilledPromise->done() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:135
 React\Promise\Promise::React\Promise\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/FulfilledPromise.php:42
 React\Promise\FulfilledPromise->done() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:135
 React\Promise\Promise::React\Promise\{closure}() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at /Users/max/git/tools/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at n/a:n/a
 call_user_func() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Util/ProcessExecutor.php:343
 Composer\Util\ProcessExecutor->countActiveJobs() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Util/Loop.php:98
 Composer\Util\Loop->wait() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Installer/InstallationManager.php:497
 Composer\Installer\InstallationManager->waitOnPromises() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Installer/InstallationManager.php:470
 Composer\Installer\InstallationManager->executeBatch() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Installer/InstallationManager.php:390
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Installer/InstallationManager.php:282
 Composer\Installer\InstallationManager->execute() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Installer.php:752
 Composer\Installer->doInstall() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Installer.php:281
 Composer\Installer->run() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Command/InstallCommand.php:141
 Composer\Command\InstallCommand->execute() at /Users/max/git/tools/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /Users/max/git/tools/composer/vendor/symfony/console/Application.php:1005
 Symfony\Component\Console\Application->doRunCommand() at /Users/max/git/tools/composer/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Console/Application.php:332
 Composer\Console\Application->doRun() at /Users/max/git/tools/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /Users/max/git/tools/composer/vendor/composer/composer/src/Composer/Console/Application.php:128
 Composer\Console\Application->run() at /Users/max/git/tools/composer/vendor/composer/composer/bin/composer:74

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

```

#### How to reproduce

Not really to reproduce but loading the `autoload.php` while `vendor/autoload.php` is not available should be testable.

#### Expected behavior

`Autoloader::load` should not throw an exception in case that `vendor/autoload.php` is missing. Maybe some kind of `NoopAutoloader` might be something. This would only be necessary during `composer install` of a project which does not initially have a `vendor/autoload.php`.

**Comment by Seldaek** [comment]
I don't want to stress anyone here, I don't know what the impact of this issue will be exactly, nor how widespread the use of this package is, but we do plan to release Composer 2.2 on the 22nd so I just wanted to give you a heads up that this will maybe become more pressing then. If you think that'll wreak havoc and you can't get a fix out in time let me know.

cc @weierophinney

**Comment by weierophinney** [comment]
I don't even understand how this gets triggered. :smile: 

@boesing , have you had a chance to look into this at all?

**Comment by Ocramius** [comment]
It's at the very core of most laminas packages, but:

 1. We could declare it incompatible with `composer-plugin-api:>=2.2.0`, perhaps?
 2. Package is slowly being phased out: perhaps the above really is a decent solution

**Comment by Seldaek** [comment]
The way this would get triggered is if a plugin requires laminas/laminas-zendframework-bridge - I don't know if you have any composer plugins in mind that would be in the list of dependents here https://packagist.org/packages/laminas/laminas-zendframework-bridge/dependents?order_by=downloads&requires=require ?

During plugin initialization it would then require the `files` autoload from this package, which tries to locate the Composer autoloader. That is fine in general but if it's not there because it's the initial install and vendor dir isn't fully built yet, this fails at https://github.com/laminas/laminas-zendframework-bridge/blob/1.5.x/src/Autoloader.php#L75

IMO simply removing the throw there would be an OK fix. If you didn't run composer install most likely you won't have this package's files being executed anyway, so this is an overly defensive check. Simply not loading the autoloader in the plugin context would most likely be fine I suppose, but I guess it depends on the plugin and why it is requiring this package. Or perhaps Composer has a bug somewhere..

Anyway it'd help if @boesing would post the full `composer install` output which should show which plugin is being activated when the exception occurs.

**Comment by Seldaek** [comment]
Looked up package types in the packagist DB, and it seems like these 3 are candidates for triggering the issue:

1. https://packagist.org/packages/laminas/laminas-component-installer (not requiring the bridge in the latest release, so there's an upgrade path, but still quite a bit of old versions being installed)
2. https://packagist.org/packages/laminas-api-tools/api-tools-asset-manager ~300 installs/day
3. https://packagist.org/packages/laminas/laminas-skeleton-installer ~50 installs/day

And indeed simply requiring any of them in an empty dir creating a new composer.json & vendor dir triggers the issue:

![image](https://user-images.githubusercontent.com/183678/146831072-1b717047-20e8-43c1-bbd2-cd68d043880d.png)


If you can't release a fix here, I'd at least make sure the packages 2/3 above have a version not relying on the bridge anymore if possible.

@ocramius IMO declaring an incompatibility with Composer 2.2 won't really help as people using older releases will still experience issues, and Composer 2.2 will simply resolve the old broken release instead of the latest.

You're definitely better judges than me of whether these 3 plugins are widespread and will cause a mess.. so if you think it's warranted I can also add an exclusion in Composer so this package's files autoload does not get loaded when initializing plugins. Should be an easy enough fix and as we're the ones breaking BC to some extent by changing assumptions I'm open to help out here.

**Comment by boesing** [comment]
I am not able to post a full output as it wont be that useful anyways. there are too many private packagist components in there.

But it happens in combination with laminas-dependency-plugin and the bridge. 

the reason is that we do search for composer autoload.php at runtime which might not be available with composer 2.2+

I think it should work having a noop autoloader in case the `vendor/autoload.php` is not available. As of now, we only throw an exception if it is not available which then breaks the install process.

----

nice, thanks jordi. will see if I can find a fix tomorrow evening. All issues are traced back to this package, right?

**Comment by Ocramius** [comment]
> and Composer 2.2 will simply resolve the old broken release instead of the latest.

Agreed, but it's still possible to ask people to run the latest version (and to check for that), while a solution is being investigated.

**Comment by boesing** [comment]
I've created a simple-enough solution in #90 
If the class loader could not be found, we simply do not register the bridge autoloaders and might be good to go.

**Comment by Ocramius** [comment]
Closing as per #90

**Comment by Seldaek** [comment]
Glad this got fixed! To avoid ruining everyone's holiday season tho I figured it'd be safer to make sure Composer skips the file in versions not containing the fix.. https://github.com/composer/composer/commit/54123e4093c7770ec3d807263274ce750302bc4b
